#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BleSample.Droid.Resource", IsApplication=true)]

namespace BleSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int CharacteristicNameLabel = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int CharacteristicUuidLabel = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int DeviceAddressLabel = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int DeviceNameLabel = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int ReadButton = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int ReadText = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int RightArrow = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int Text1 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Text2 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Text3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Text4 = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int WriteButton = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int WriteText = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int deviceList = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int relativeLayout1 = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int scanButton = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int serviceList = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Characteristic = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CharacteristicsList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ServiceList = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ScanButton = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ble_not_supported = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int error_bluetooth_not_supported = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
